name: ValidateDotnetBuild
# This workflow is triggered on pushes to the repository.
on: 
  push:
     paths:
      - 'apis/poi/**'

env:
  BuildConfig: Release
  SolutionFile: /apis/poi/poi.sln
  ProjectFile: /apis/poi/tests/UnitTests/UnitTests.csproj

jobs:
  build:
    # Job name is ValidateDotNet
    name: ValidateDotNet
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    
    
    
      # First check the code out
      - name: Check out
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow
       
      - name: Build
        run: dotnet build
             --configuration ${{env.BuildConfig}}
        
      #  with:
      #    who-to-greet: 'Mona the Octocat'
     #   id: hello
      # This step prints an output (time) from the previous step's action.
      #- name: Echo the greeting's time
    # run: echo 'The time was ${{ steps.hello.outputs.time }}.'
