name: ValidateDotnetBuild
# This workflow is triggered on pushes to the repository.
on: 
  push:
     paths:
      - 'apis/poi/**'



jobs:
  build:
    # Job name is ValidateDotNet
    name: ValidateDotNet
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    
    
    
      # First check the code out
      - name: Check out
        uses: actions/checkout@v2
      
      - name: setup .net core
        uses: actions/setup-dotenet@v1
        with:
          dotenet-version: 3.1.301
          
      - name: Install dependencies
        run: dotnet restore 
     
      - name: Build
        run: dotnet build --configuration Release --no-restore
             
        
      #  with:
      #    who-to-greet: 'Mona the Octocat'
     #   id: hello
      # This step prints an output (time) from the previous step's action.
      #- name: Echo the greeting's time
    # run: echo 'The time was ${{ steps.hello.outputs.time }}.'
